// AUTHENTICATIONS
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_SUCCESS_AUTH0 = "LOGIN_SUCCESS_AUTH0";
export const LOGIN_FAILURE_AUTH0 = "LOGIN_FAILURE_AUTH0";
//export const SET_CURRENT_USER_AUTH0 = "SET_CURRENT_USER_AUTH0"
//export const DELETE_CURRENT_USER_AUTH0 = "DELETE_CURRENT_USER_AUTH0"
// ACCOUNT
export const REFRESH_ACCOUNT_DATA = "REFRESH_ACCOUNT_DATA";
// News && Notice
export const GET_NEWS = "GET_NEWS";
export const LOADING_NEWS = "LOADING_NEWS";
export const GET_NOTICE = "GET_NOTICE";
export const LOADING_NOTICE = "LOADING_NOTICE";
// CONTROL
export const GET_USER_CONTROL = "GET_CONTROL";
export const LOADING_USER_CONTROL = "LOADING_CONTROL";
// OPERATIONS PROJECTS
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
// OPERATIONS TASKS
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const GET_TASKS = "GET_TASKS";
export const TASKS_LOADING = "TASKS_LOADING";
// PRICE LIST
export const GET_PRICE_LIST = "GET_PRICE_LIST";
export const LOADING_PRICE_LIST = "LOADING_PRICE_LIST";
// SALE PARTNERS
export const GET_SALE_PARTNERS = "GET_SALE_PARTNERS";
export const LOADING_SALE_PARTNERS = "LOADING_SALE_PARTNERS";